---
name: Regexp-Common-debian
version: v0.2.11
author:
  - 'Eric Pozharski <whynot@cpan.org>'
abstract: regexps for Debian specific strings
license: lgpl
resources:
  license: http://opensource.org/licenses/lgpl-license.php
build_requires:
  File::Temp: ''
  Test::Differences: ''
  Test::More: ''
  YAML::Syck: ''
requires:
  Regexp::Common: ''
  perl: v5.6.0
  version: 0.5
configure_requires:
  Module::Build: 0.340201
provides:
  Regexp::Common::debian:
    file: lib/Regexp/Common/debian.pm
    version: v0.2.11
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
