---
match_package:
  -
    - a
    - '-'
  -
    - 0
    - '-'
  -
    - '-'
    - '-'
  -
    - -a
    - '-'
  -
    - -0
    - '-'
  -
    - -a-
    - '-'
    - a-
  -
    - -0-
    - '-'
    - 0-
  -
    - -ab
    - '-'
    - ab
  -
    - -a0
    - '-'
    - a0
  -
    - -0a
    - '-'
    - 0a
  -
    - +
    - '-'
  -
    - +a
    - '-'
  -
    - +0
    - '-'
  -
    - +a+
    - '-'
    - a+
  -
    - +0+
    - '-'
    - 0+
  -
    - +ab
    - '-'
    - ab
  -
    - +a0
    - '-'
    - a0
  -
    - +0a
    - '-'
    - 0a
  -
    - .
    - '-'
  -
    - .a
    - '-'
  -
    - .0
    - '-'
  -
    - .a.
    - '-'
    - a.
  -
    - .0.
    - '-'
    - 0.
  -
    - .ab
    - '-'
    - ab
  -
    - .a0
    - '-'
    - a0
  -
    - .0a
    - '-'
    - 0a
  -
    - '#'
    - '-'
  -
    - '#a'
    - '-'
  -
    - '#0'
    - '-'
  -
    - 'a#'
    - '-'
  -
    - '0#'
    - '-'
  -
    - '#a0'
    - '-'
    - a0
  -
    - 'a#0'
    - '-'
  -
    - 'a0#'
    - '-'
    - a0
  -
    - /
    - '-'
  -
    - /a
    - '-'
  -
    - a/
    - '-'
  -
    - ab/
    - '-'
    - ab
  -
    - a/b
    - '-'
  -
    - /ab
    - '-'
    - ab
  -
    - _
    - '-'
  -
    - _a
    - '-'
  -
    - a_
    - '-'
  -
    - a_b
    - '-'
  -
    - ab
    - +
    - ab
  -
    - a-
    - +
    - a-
  -
    - a+
    - +
    - a+
  -
    - a.
    - +
    - a.
  -
    - a0
    - +
    - a0
  -
    - 0a
    - +
    - 0a
  -
    - 01
    - +
    - 01
  -
    - 0-
    - +
    - 0-
  -
    - 0+
    - +
    - 0+
  -
    - 0.
    - +
    - 0.
  -
    - abc
    - +
    - abc
  -
    - a-b
    - +
    - a-b
  -
    - ab-
    - +
    - ab-
  -
    - a+b
    - +
    - a+b
  -
    - ab+
    - +
    - ab+
  -
    - a.b
    - +
    - a.b
  -
    - ab.
    - +
    - ab.
  -
    - 0ab
    - +
    - 0ab
  -
    - a0b
    - +
    - a0b
  -
    - ab0
    - +
    - ab0
  -
    - 1a0
    - +
    - 1a0
  -
    - a10
    - +
    - a10
  -
    - 210
    - +
    - 210
  -
    - abcdefghijklmnopqrstuvwxyz
    - +
    - abcdefghijklmnopqrstuvwxyz
  -
    - 0123456789
    - +
    - 0123456789
